#!/bin/sh
set -aeuo pipefail

if [ "$#" -lt 1 ]
then
    echo "Usage: $0 <env>" >&2
    exit 1
fi

ENV_FILE="$1"
. "$ENV_FILE"
shift

restic diff $(restic snapshots --latest 2 --json | jq -r '.[].id') "$@"